export const AUTH_MESSAGES = {
  INVALID_CREDENTIALS: 'Email ou senha incorretos',
  USER_EXISTS: 'Este email ja esta registrado',
  WEAK_PASSWORD: 'Senha deve ter pelo menos 8 caracteres',
  NETWORK_ERROR: 'Erro de conexao. Tente novamente',
  DEFAULT_ERROR: 'Ocorreu um erro inesperado',
  WELCOME: 'Bem-vindo!',
  LOGIN_TAB: 'Entrar',
  SIGNUP_TAB: 'Criar Conta',
  FULL_NAME_LABEL: 'Nome completo',
  EMAIL_LABEL: 'E-mail',
  PASSWORD_LABEL: 'Senha',
  CONFIRM_PASSWORD_LABEL: 'Confirmar Senha',
  TERMS_LABEL: 'Concordo com os termos de servico',
  SUBMIT_LOGIN: 'Entrar',
  SUBMIT_SIGNUP: 'Criar Conta',
  PROCESS_LOADING: 'Processando...',
  FORGOT_PASSWORD: 'Esqueceu a senha?',
  NO_ACCOUNT: 'Nao tem conta? Criar uma',
  HAS_ACCOUNT: 'Ja tem conta? Entrar',
}
